### ISSUE TITLE
Argument #4 ($content) must be of type array, null given in ErrorUtils.php

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/thirtybees#1576]
The log file in my TB /log directory produces the following series of messages repeatedly. I have no idea what this is about. But as I am still hunting a bug they could hide something interesting:
`*ERROR* 	2022/12/02 - 12:50:47: Fatal Error: Uncaught TypeError: Thirtybees\Core\Error\ErrorDescriptionCore::setSource(): Argument #4 ($content) must be of type array, null given, called in /home/public/sites/www.webshop.nl/classes/error/ErrorUtils.php on line 98 and defined in /home/public/sites/www.webshop.nl/classes/error/ErrorDescription.php:153
Stack trace:
#0 /home/public/sites/www.webshop.nl/classes/error/ErrorUtils.php(98): Thirtybees\Core\Error\ErrorDescriptionCore->setSource()
#1 /home/public/sites/www.webshop.nl/classes/error/ErrorHandler.php(121): Thirtybees\Core\Error\ErrorUtilsCore::describeException()
#2 [internal function]: Thirtybees\Core\Error\ErrorHandlerCore->uncaughtExceptionHandler()
#3 {main}
  thrown at line 153 in file classes/error/ErrorDescription.php`

**Comment by getdatakick** [comment]
Bugs in error reporting engine are the worst

**Comment by getdatakick** [comment]
Looks like the problem is that the file that caused the error doesn't exists... I don't know how that happens???

Anyways, fix for this issue is coming up soon
