### ISSUE TITLE
Message: ThirtyBeesDatabaseException: Not unique table/alias: 'c'  Location: classes/Group.php line 426

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1599]
When installing the latest version of Omniprice module from CodeCanyon (1.0.15) I'm experiencing the following error when opening 'configure' page:

```sql
SELECT COUNT(*)
FROM `ps_customer` c
LEFT JOIN `ps_customer` `c` ON cg.`id_customer` = c.`id_customer`
WHERE (cg.`id_group` = 1 ) AND (c.`deleted` != 1) LIMIT 1
```

```
#0  classes/Group.php(426)
#1  classes/db/Db.php(851): ()
#2  classes/db/Db.php(486): DbCore->displayError(string(160): "SELECT COUNT(*)\nFROM `ps_customer` c\nLEFT JOIN `ps_customer` `c` ON cg.`id_cus"...)
#3  classes/db/Db.php(774): DbCore->query(string(160): "SELECT COUNT(*)\nFROM `ps_customer` c\nLEFT JOIN `ps_customer` `c` ON cg.`id_cus"...)
#4  classes/db/Db.php(801): DbCore->getRow(string(160): "SELECT COUNT(*)\nFROM `ps_customer` c\nLEFT JOIN `ps_customer` `c` ON cg.`id_cus"..., true)
#5  classes/Group.php(426): DbCore->getValue(DbQuery#1)
#6  modules/gm_omniprice/gm_omniprice.php(1100): GroupCore->getCustomers(true)
#7  modules/gm_omniprice/gm_omniprice.php(1062): Gm_OmniPrice->findEmptyGroups()
#8  modules/gm_omniprice/gm_omniprice.php(174): Gm_OmniPrice->displayInformationPanel()
#9  controllers/admin/AdminModulesController.php(1592): Gm_OmniPrice->getContent()
#10 controllers/admin/AdminModulesController.php(1454): AdminModulesControllerCore->postProcessCallback()
#11 classes/controller/Controller.php(191): AdminModulesControllerCore->postProcess()
#12 classes/Dispatcher.php(851): ControllerCore->run()
#13 adminxxxx/index.php(58): DispatcherCore->dispatch()
```

Best regards!

**Comment by therampagerado** [comment]
A fix sugested by https://codecanyon.net/user/GreenMouseStudio:

"I see it, it clearly is a TB bug related to counting customers. Line 434 of Group.php in TB has an error. It should have ->from(‘customer_group’, ‘cg’), not ->from(‘customer’, ‘c’)"

I believe he means line 423.

**Comment by getdatakick** [comment]
Indeed, this is a bug introduced in 2017. This method is actually not used by core at all, and probably not by many modules, otherwise this bug would have to be discovered much sooner.
