### ISSUE TITLE
Search class Database Exception

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/thirtybees#1663]
#### Message:
`ThirtyBeesDatabaseException: Deadlock found when trying to get lock; try restarting transaction`

#### Location:
`classes/Search.php` line `552`

#### Stacktrace
```
#0 classes/Search.php(552)
#1 classes/db/Db.php(232): ()
#2 classes/db/Db.php(441): DbCore->displayError(string(292): "\n\t\t\t\t\t\tINSERT IGNORE INTO ps_search_word (id_lang, id_shop, word)\n\t\t\t"...)
#3 classes/db/Db.php(573): DbCore->query(string(292): "\n\t\t\t\t\t\tINSERT IGNORE INTO ps_search_word (id_lang, id_shop, word)\n\t\t\t"...)
#4 classes/Search.php(552): DbCore->execute(string(292): "\n\t\t\t\t\t\tINSERT IGNORE INTO ps_search_word (id_lang, id_shop, word)\n\t\t\t"..., false)
#5 admin/searchcron.php(50): SearchCore::indexation("1")
```

**Comment by getdatakick** [comment]
Should be fixed by #1799 and #1783
