### ISSUE TITLE
Warnings for non-existing address

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1739]
### Message:
`Trying to access array offset on value of type bool`

### Location:
`classes/Product.php line 930`

### Stacktrace
```
#0  classes/Product.php(930)
#1  classes/Cart.php(541): ProductCore::getPriceStatic(2265, true, 0, 6, null, false, false, 10, false, 61909, 307132, "77353", null, true, true, Context#1)
#2  classes/Cart.php(1110): CartCore->getProducts()
#3  classes/Cart.php(859): CartCore->isVirtualCart()
#4  classes/Cart.php(3939): CartCore->getOrderTotal(true)
#5  controllers/admin/AdminCustomersController.php(920): CartCore->getSummaryDetails()
#6  classes/controller/AdminController.php(2327): AdminCustomersControllerCore->renderView()
#7  controllers/admin/AdminCustomersController.php(264): AdminControllerCore->initContent()
#8  classes/controller/Controller.php(209): AdminCustomersControllerCore->initContent()
#9  classes/Dispatcher.php(854): ControllerCore->run()
#10 iadmin2/index.php(58): DispatcherCore->dispatch()
```

**Comment by getdatakick** [comment]
Fixed by commit 4152e879715d00ae2c6a99cc7786aefe3a5243b2
