### ISSUE TITLE
 'Property Product->price is empty' in combination generator when product is enabled only in some shops

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/thirtybees#1761]
thirtybees version: edge as of yesterday

Multishop: yes

When we have a product only enabled in some of the shops we cannot use the combinations generator because of this nasty error. Product addition is done in all shop context.

When the product gets enabled in all shops the generator works as expected.

Obviously a bug from long ago as something similar is described here for store commander: https://www.storecommander.com/support/en/known-errors/865-property-product-price-is-empty-multistore.html

![image](https://github.com/thirtybees/thirtybees/assets/11251370/1ea1e77b-79b7-43b9-97c5-82d1a2bd4f77)

EXCEPTION
Message:
`ThirtyBeesException: Property Product->price is empty`

Location: `classes/ObjectModel.php line 1049`
STACKTRACE
```
#0  classes/ObjectModel.php(1049)
#1  classes/ObjectModel.php(329): ObjectModelCore->validateFields()
#2  classes/ObjectModel.php(357): ObjectModelCore->getFields()
#3  classes/ObjectModel.php(779): ObjectModelCore->getFieldsPrimary()
#4  classes/Product.php(5241): ObjectModelCore->update()
#5  classes/Product.php(5221): ProductCore->update()
#6  classes/Product.php(5128): ProductCore->setAvailableDate()
#7  controllers/admin/AdminAttributeGeneratorController.php(189): ProductCore->generateMultipleCombinations()
#8  classes/controller/AdminController.php(588): AdminAttributeGeneratorControllerCore->processGenerate()
#9  controllers/admin/AdminAttributeGeneratorController.php(153): AdminControllerCore->postProcess()
#10 classes/controller/Controller.php(198): AdminAttributeGeneratorControllerCore->postProcess()
#11 classes/Dispatcher.php(854): ControllerCore->run()
#12 admin391aj92ac/index.php(58): DispatcherCore->dispatch()
```

**Comment by therampagerado** [comment]
This fixed my issue with product generator but today I noticed new issue that I can't recall if I stumbled upon before. The same error but when duplicating products in Products list.

Unfortunately I'm unable to find what setting is causing the issue.

I'm again trying to duplicate a product that is only associated with some shops.

EXCEPTION
Message:
ThirtyBeesException: Property Product->price is empty

Location:
classes/ObjectModel.php line 1049
STACKTRACE
#0  classes/ObjectModel.php(1049)
#1  classes/ObjectModel.php(329): ObjectModelCore->validateFields()
#2  classes/ObjectModel.php(357): ObjectModelCore->getFields()
#3  classes/ObjectModel.php(606): ObjectModelCore->getFieldsPrimary()
#4  classes/Product.php(7768): ObjectModelCore->add()
#5  controllers/admin/AdminProductsController.php(828): ProductCore->add()
#6  classes/controller/AdminController.php(588): AdminProductsControllerCore->processDuplicate()
#7  controllers/admin/AdminProductsController.php(1344): AdminControllerCore->postProcess()
#8  classes/controller/Controller.php(198): AdminProductsControllerCore->postProcess()
#9  classes/Dispatcher.php(854): ControllerCore->run()
#10 admin391aj92ac/index.php(58): DispatcherCore->dispatch()

![image](https://github.com/thirtybees/thirtybees/assets/11251370/7569f78d-e922-40f7-8808-aded6a78f6c0)


I tried with a test product that I only enabled for some shops but it duplicates OK. I'll try to investigate further.

Posting this here as the error is the same. If not related I'll make a new issue.

**Comment by therampagerado** [comment]
Further details:

This bug happens when I duplicate a product that is not associated with the default shop. If it is the process is flawless all the time.

How to reproduce:

Products list in all shop context.

Make a test product and associate it with only few shops not the default. Upon save the product is visible in the Products list because of All shops context.

If you duplicate this product the error message appears Property Product-> price is empty and the product is not listed.

If you switch to some of the shops that the original product is associated the duplicated product is listed with new ID but bugs in it's settings (no price, no category association, etc. The product id is always advanced but the product itself is not duplicated properly. If we return to All shops context the duplicated product is visible now. Not a cache issue as I tested with caches turned off and cleared cache.

@getdatakick
